spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  flyway:
    locations: classpath:migrations
    url: jdbc:mysql://localhost:3306/yulkost
    user: kostya
    password: 19804731205
  datasource:
    url: jdbc:mysql://localhost:3306/yulkost
    username: kostya
    password: 19804731205
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQLDialect

server:
  address: 0.0.0.0
  port: 8080